spring.application.name=tickets

# Database Connectiuon
spring.databasesource.url=jdbc.postgresql://localhost:5432/postgres
spring.dataabse.username=admin
spring.database.password=admin

#JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/event-ticket-platform